API_KEY = ENV["LIPISHA_API_KEY"]
API_SIGNATURE = ENV["LIPISHA_API_SIGNATURE"]
API_ENVIRONMENT = "live"
STATUS_SUCCESS = "SUCCESS"
STATUS_CONFIRMED = "Completed"

FLOAT_ACCOUNT = ""
PAYOUT_ACCOUNT = ""
AIRTIME_ACCOUNT = ""

TRANSACTION_ID_CONFIRM = ""
TRANSACTION_ID_REVERSE = ""

AIRTIME_AMOUNT = 10
AIRTIME_NETWORK = ""
AIRTIME_MOBILE_NUMBER = ""
PAYOUT_MOBILE_NUMBER = ""
PAYOUT_AMOUNT = 10


ACCOUNT_NAME = ""
ACCOUNT_ADMIN = ""


TEST_USER_NAMES = ""
TEST_USER_ROLE = ""
TEST_USER_MOBILE = ""
TEST_USER_EMAIL = ""
TEST_USER_LOGIN = ""

TEST_TX_ACCOUNT_NAME = ""
TEST_TX_ACCOUNT_NUMBER = ""
TEST_TX_ACCOUNT_BANK_NAME = ""
TEST_TX_ACCOUNT_BANK_BRANCH = ""
TEST_TX_ACCOUNT_BANK_ADDRESS = ""
TEST_TX_ACCOUNT_SWIFT_CODE = ""
TEST_TX_ACCOUNT_MANAGER = ""

CARD_AMOUNT = 10
CARD_CURRENCY = ""
CARD_ACCOUNT = ""
CARD_NUMBER = ""
CARD_ADDRESS1 = ""
CARD_ADDRESS2 = ""
CARD_EXPIRY = ""
CARD_NAMES = ""
CARD_COUNTRY = ""
CARD_STATE = ""
CARD_ZIP = ""
CARD_SECURITY_CODE = ""


CARD_COMPLETE_TX_INDEX = ""
CARD_COMPLETE_TX_REF = ""

CARD_REVERSE_TX_INDEX = ""
CARD_REVERSE_TX_REF = ""

CARD_VOID_TX_INDEX = ""
CARD_VOID_TX_REF = ""
