API_KEY = ENV["LIPISHA_API_KEY"]
API_SIGNATURE = ENV["LIPISHA_API_SIGNATURE"]
API_ENVIRONMENT = "live"
STATUS_SUCCESS = "SUCCESS"
STATUS_CONFIRMED = "Completed"

FLOAT_ACCOUNT = ""
PAYOUT_ACCOUNT = ""
AIRTIME_ACCOUNT = ""

TRANSACTION_ID_CONFIRM = ""
TRANSACTION_ID_REVERSE = ""
