API_KEY = ENV["LIPISHA_API_KEY"]
API_SIGNATURE = ENV["LIPISHA_API_SIGNATURE"]
API_ENVIRONMENT = "live"
STATUS_SUCCESS = "SUCCESS"
STATUS_CONFIRMED = "Completed"

FLOAT_ACCOUNT = ""
PAYOUT_ACCOUNT = ""
AIRTIME_ACCOUNT = ""

TRANSACTION_ID_CONFIRM = ""
TRANSACTION_ID_REVERSE = ""

AIRTIME_AMOUNT = 10
AIRTIME_NETWORK = ""
AIRTIME_MOBILE_NUMBER = ""
PAYOUT_MOBILE_NUMBER = ""
PAYOUT_AMOUNT = 10


ACCOUNT_NAME = ""
ACCOUNT_ADMIN = ""


TEST_USER_NAMES = ""
TEST_USER_ROLE = ""
TEST_USER_MOBILE = ""
TEST_USER_EMAIL = ""
TEST_USER_LOGIN = ""
